plugins {
    id 'java'
}

group = 'org.game'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    implementation 'org.frontier:Engine'
    implementation platform("org.lwjgl:lwjgl-bom:3.4.3")

    implementation "org.joml:joml:1.10.9"
    implementation "org.lwjgl:lwjgl"
    implementation "org.lwjgl:lwjgl-glfw"
    implementation "org.lwjgl:lwjgl-glfw::natives-windows"
    runtimeOnly "org.lwjgl:lwjgl:3.4.3:natives-windows"
    runtimeOnly "org.lwjgl:lwjgl-glfw:3.4.3:natives-windows"
}

test {
    useJUnitPlatform()
}